# This file generated by Quarto; do not edit by hand.

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    from shiny import render, reactive, ui
    import yfinance as yf
    import pandas as pd
    import matplotlib.pyplot as plt
    import matplotlib.dates as mdates
    from datetime import datetime, timedelta

    current_date = datetime.now()
    one_year_ago = current_date - timedelta(days=365)

    # ========================================================================

    @render.text
    @reactive.event(lambda: input.go(), ignore_none=False)
    def text():
        if input.go() > 0:
            return " " + input.ticker()
        else:
            return " " + "^GSPC"

    # ========================================================================

    @reactive.Calc
    def data():
        return yf.download(input.ticker(), start=current_date, end=one_year_ago)

    # ========================================================================

    ui.input_text("ticker", "Enter a ticker:")
    ui.input_action_button("go", "Get Data", width="100px")

    # ========================================================================




_static_assets = ["stock-dashboard_files"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "stock-dashboard.html",
    server,
    static_assets=_static_assets,
)
